blank_issues_enabled: true
contact_links:
  - name: Questions, discussions
    url: https://github.com/neherlab/covid19_scenarios/issues/18
    about: This thread is dedicated to questions and discussions about the "COVID-19 scenarios" application as well as the science behind it.
